### PR TITLE
abbreviate and add spaces to financial chart indicator menu

### PR DESCRIPTION
**Pull request by davidnegley**
Closes tfs 257490

### CODE REVIEW

**Comment by ig-ealbert** [comment]
@davidnegley This will affect more than the Angular chart.  If the indicator names are all changed from enumeration values to the regular names, it would be best if they were all localizable.  That would add a lot of entries to the jQuery i18n files.  @yoshimis Do you have any preference for how these indicator menu items are displayed?  (Ex. with or without spaces, EN only or localizable?)

**Comment by ig-ealbert** [comment]
@kdinev @davidnegley I assume the indicator names were changed from enumerations to the actual names on purpose.  If this is the case, then yes, they should be added to the locale files.  But if they can be changed back to the enumerations, that works even better.

**Comment by davidnegley** [comment]
yes, these strings will need to be localized at some point.  they were not localized in 18.1.

**Comment by davidnegley** [comment]
how would it be better to go back to the unspaced enum names?

**Comment by ig-ealbert** [comment]
We don't localize enumerations since the exact enumeration text like "BollingerBands" needs to be used in the code.  But when it's a description term like "Bollinger Bands", then we localize it.

**Comment by davidnegley** [comment]
this does not persuade me to take a step backwards.  i can proceed with making these strings localizable, though.

**Comment by ig-ealbert** [comment]
Yes, that solution is fine.  Please let me or @yoshimis know when they are ready and where they are.

**Comment by davidnegley** [comment]
Okay, the strings are now localizable an are in the usual spot with the other toolbar strings

**Comment by kdinev** [comment]
@davidnegley There's conflict with the master branch. I just merged another PR, which probably caused the conflict. Can you take a look?

**Pull request merged**
