### PR TITLE
fix issue if component's container is resized while the container is …

### PR DESCRIPTION
**Pull request by gmurray81**
…set to display: none

Closes internal bug: 242424

### CODE REVIEW

**Comment by kdinev** [comment]
@gmurray81 The indentation looks a little odd. Is this just the GitHub display?

**Comment by gmurray81** [comment]
Seems ok to my eyes. How do you guys have your tabs configured in your editors? Or it could be because I started the change in the VS IDE and copied it over.

**Comment by kdinev** [comment]
@gmurray81 For ignite-ui we have tabs. I was referring to this view: https://github.com/IgniteUI/ignite-ui/pull/1425/files

**Comment by gmurray81** [comment]
It looks fine in editor. Seeming like the difference is either my VS IDE or my VS code inserted spaces instead of tabs. Want me to convert?

**Comment by kdinev** [comment]
@gmurray81 Yes, please. I'm surprised your VSCode didn't get this: https://github.com/IgniteUI/ignite-ui/blob/master/.vscode/settings.json

**Comment by gmurray81** [comment]
I think its because I started the fix in VS IDE, since that's where some of my testing samples are, and then copied the code across to VSCode later, it must have preserved the spaces.

**Pull request merged**
