### PR TITLE
Fix for bug 238125 - When headerText contains HTML string the column cell data is broken (contains escaped html)

### PR DESCRIPTION
**Pull request by petkozhekov**
Fix for bug 238125 - When headerText contains HTML string the column cell data is broken (contains escaped html)

### Additional information related to this pull request:

The issue is caused by the aria-label attribute which accepts the value of the headerText option. When there are html tags in the header text some of the symbols need to be escaped so the generated html is correct.

### CODE REVIEW

**Comment by kdinev** [comment]
There is an encode function in until. You should use it instead.

**Comment by petkozhekov** [comment]
Currently the "encode" method is in the infragistics.templating.js file. If I use it in the infragistics.util.js file it will create a dependency between the two. Is it a good idea to move the encode method into the util file and then use it?

**Comment by kdinev** [comment]
@petkozhekov At least create an encode function in util. I will think about adding a dependency in the templating file on util, and removing the encode method from the templating file. Btw, doesn't the `igGrid` already depend on templating, and thus it has access to encode coming from templating?

**Comment by ChronosSF** [comment]
@kdinev The AMD support for templating already loads util and util.jquery .

**Pull request merged**
