### PR TITLE
Creating new file structure by Moving, deleting and adding new files.

### PR DESCRIPTION
**Pull request by desig9stein**
Closes # .  

Additional information related to this pull request:

All themes, which are NOT bootstrap related will have “/images” “framework.less”, “variable.less” and “infragistics.theme.less/css”.

So far only "Metro" and "infragistics2012" don't have “framework.less” and they have empty “variable.less” we need to translate them from .css to .less

1.	NOT Bootstrap3 related themes
a.	Infragistics ( styles / themes / infragistics / infragistics.theme.css )
b.	Infragistics2012 ( styles / themes / infragistics2012 / infragistics.theme.css )
c.	ios ( styles / themes / ios / infragistics.theme.css )
d.	metro ( styles / themes / metro / infragistics.theme.css )

Bootstrap 3 and All themes which are bootstrap 3 related will have “/images”, “variable.less” and “infragistics.theme.less/css”.

1.	Bootstrap 3 related themes:
a.	Bootstrap 3 ( styles / themes / bootstrap3 / infragistics.theme.css )
b.	flatly ( styles / themes / bootstrap3 / flatly / infragistics.theme.css )
c.	yeti ( styles / themes / bootstrap3 / yeti / infragistics.theme.css )
d.	superhero ( styles / themes / bootstrap3 / superhero / infragistics.theme.css )

All Bootstrap 3  themes will be under one single folder “/bootstrap3”. Inside “/bootstrap3” folder, we will have also a folder called “_shared-styles” and inside another one called “less”. The “less” folder will contain all files that are shared betwine all bootstrap 3 related themes. 
The shared files are “framework.less”, “infragistics.igniteui.theme.less”, “infragistics.jqueryui.theme.less”, “mixins.less” and “variables-igniteui.less”.

For bootstrap 4 the File structure will be the same as for Bootstrap 3.

### CODE REVIEW

**Comment by kdinev** [comment]
@mpavlinov @bazal4o @zdrawku All demos referring to bootstrap themes should be updated with the new paths.

**Comment by desig9stein** [comment]
@kdinev  I will make another pull request request for the readme file so you can merge this one now.

**Comment by ig-ealbert** [comment]
@IG-Stanimir-Dimitrov @desig9stein Could you please help me to understand what I need to do here?  I see that a couple of readme files were changed.  Is one new and the other just needs to be updated?

**Comment by IG-Stanimir-Dimitrov** [comment]
@ig-ealbert , we are changing the Ignite UI themes file structure to make them more maintainable in the long run. The readme files were updated in the process so the localized readmes also need to be updated. These are not new, just require updating.

**Pull request merged**
