### PR TITLE
BUG-2236456 // 09.12.2016 // M.Popov //

### PR DESCRIPTION
**Pull request by desig9stein**
Font Double definition Fix

### CODE REVIEW

**Comment by kdinev** [comment]
@desig9stein Can you pull master into your branch pls?

**Comment by kdinev** [comment]
Can you pull master into your branch?

**Comment by desig9stein** [comment]
@kdinev, close this PR, me and @damyanpetev decide, not to do that change for now because it cause problems.

**Comment by kdinev** [comment]
@desig9stein Alright, I will do that!

**Pull request closed without merging**
