### PR TITLE
Fix issue #203 - Toolbar button does not work properly for a selected content range if a text is initially selected by double-tapping, and the selection is changed by mouse dragging.

### LINKED ISSUE #203: Toolbar button does not work properly for a selected content range if a text is initially selected by double-tapping, and the selection is changed by mouse dragging.
Toolbar button does not work properly for a selected content range if a text is initially selected by double-tapping, and the selection is changed by mouse dragging.

### PR DESCRIPTION
**Pull request by Aleksandyr**
This fixes #203

### CODE REVIEW

**Comment by mpavlinov** [comment]
There are some jsHint errors that you need to fix.

**Comment by mpavlinov** [comment]
Now there are some JSCS errors that you need to fix.

**Comment by Aleksandyr** [comment]
Should i fix the errors in infragistics.util.js file, the changes there isn't from my fix, but it fails again?

**Comment by mpavlinov** [comment]
Only the ones in the igHtmlEditor

**Comment by mpavlinov** [comment]
Now you need to add some unit test on the code that you added.

**Pull request merged**
