### PR TITLE
#56 The description of 'readOnly' option for the igCheckbo…

### LINKED ISSUE #56: The description of 'readOnly' option for the igCheckboxEditor can be improved
Update/Improve option comment:
Gets/Sets the readonly attribute. Does not allow editing. Disables changing the checkbox state. On submit the current value is sent into the request

### PR DESCRIPTION
**Pull request by IvayloG**
…xEditor can be improved

closes #56

### CODE REVIEW

**Comment by kdinev** [comment]
Create a public issue about this and associate the pull request with it.

**Comment by IvayloG** [comment]
It is Internal. Should I create public issue about it regardless of being Internal or Public in TFS?

**Comment by kdinev** [comment]
Yes. Also merge master to resolve the conflicts.

**Comment by IvayloG** [comment]
Closes #56

**Comment by kdinev** [comment]
If you put closes/fixes in a comment, it wouldn't close the issue. It needs to be in the title or description.

**Comment by kdinev** [comment]
Duplucate of #58

**Pull request closed without merging**
